[extension]
name = "vectorize"
repository = "https://github.com/tembo-io/pg_vectorize"
license = "PostgreSQL"
description = "The simplest way to orchestrate vector search on Postgres."
homepage = "https://github.com/tembo-io/pg_vectorize"
documentation = "https://github.com/tembo-io/pg_vectorize"
categories = ["orchestration", "machine_learning"]
version = "0.22.0"
loadable_libraries = [{ library_name = "vectorize", requires_restart = true }]

[build]
postgres_version = "15"
platform = "linux/amd64"
